name: CD Pipeline

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Add environment specification
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Build and Deploy Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'notepadplus-api'
        package: './NotepadPlusApi'
        
    - name: Build and Deploy Frontend
      uses: Azure/static-web-apps-deploy@v1
      with:
        action: "upload"  # Required action parameter
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        app_location: "/Frontend-React"
        api_location: ""  # Empty if not using Azure Functions
        output_location: "build"
        skip_app_build: false 

    # Add environment configuration
    - name: Setup Environment
      run: |
        echo "REACT_APP_API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
        echo "REACT_APP_ENVIRONMENT=production" >> $GITHUB_ENV 