name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Add Java setup for Dependency Check
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # Add SonarCloud detailed analysis
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=notepadplus
          -Dsonar.organization=your-org
          -Dsonar.sources=.
          -Dsonar.exclusions=**/*.test.ts,**/*.test.tsx
          -Dsonar.tests=**/*.test.ts,**/*.test.tsx
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
    
    # Add Snyk security scan
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Run OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:5000'
        
    # Update the Dependency Check step
    - name: Run Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'NotepadPlus'
        path: '.'
        format: 'HTML'
        args: >
          --scan .
          --failOnCVSS 7
          --enableRetired
        
    - name: Upload Security Reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          **/dependency-check-report.html
          **/zap-scan-report.html 